---
tags: ["panic", "debug", "backtrace", "error", "runtime", "runtime error", "abort"]
---

# 9.1 panic!
: 해결불가능한 중대한 에러 in runtime

1. System 적 문제 발생시 → panic  
2. panic 명시시 → panic

⇒ panic 발생시 프로그램을 탈출한다

<br/>

## Panic시 메모리 정리

1. Unwinding Stack
    
    프로그램에서 스택에 불러온 함수를 다 정리하고 종료한다
    
2. Aborting
    
    프로그램을 종료하고 운영체제에서 스택을 정리한다
    
    ```rust
    //toml file
    [profile.release]
    panic = 'abort'
    ```
    
<br/>

## Panic 매크로 사용

```rust
fn main() {
    panic!("crash and burn");
}

$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/panic`
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

> 해당 위치에서 panic!으로 프로그램이 종료  
> panic 위치 명시, `backtrace`로 디버깅가능

<br/>

## Backtrace

: panic을 불러올 때 쓰여진 모든 함수의 list   
⇒ 문제가 된 부분 확인 가능 == list 중 내가 짠 코드

<br/>

### Backtrace 띄우기
`RUST_BACKTRACE=1 cargo run` 사용

```bash
RUST_BACKTRACE=1 cargo run

stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:159:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/slice/index.rs:260:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/vec/mod.rs:2703:9
   6: test_error::main
             at ./src/bin/test_error.rs:4:22
   7: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

> 위의 코드가 아래 코드로 인해 호출된 함수  
> 위에서 아래로 읽으면 문제가 되는 코드를 **호출한 함수**를 확인가능  
> 위에서 아래로 읽으면서 **origin** of problem 찾기  
> 당연히 문제의 근원은 내가 짠 코드 파일에 있다 = `./src/bin/test_error.rs:4`
